const TYPE_MAP={3:'V',7:'◆',11:'V',14:'◆',18:'V'};
const STORAGE_KEY='album-digitale-encrypted-v1';
const QR_A="AD1.eyJ2IjoxLCJwYWNrIjoiREVNTy1RUi0wMDEiLCJjYXJkcyI6W3siaWQiOjQsImsiOiJPQS15SWItOFI1c3lGRlJSVllJT1Nua0RQX08wTGZIOUp4bkhEbW8xaDZzIn0seyJpZCI6NywiayI6ImlnYWl0bEx4Y0FaUFVEbWw1T1I0TzN5MTRZVjNHWV9DdF9IWkxEejVJUjAifSx7ImlkIjoxMSwiayI6ImllUlNXN0FQbExuMUxWTjAzNEtmTklqLTh4bnJOeWlhdXlzVDNVZUgzN28ifSx7ImlkIjoxNCwiayI6IjJSeG5pTXN6M01xWEVQZlcwRnotM3lhNF96b25xR2xBRV9Wbnl6eEpfNFkifSx7ImlkIjoxOCwiayI6IjFiQVJnWk1wZ3Y3NDBTc2tyQkVSMDNJd2I5WDhmcVRKMzEzUC1BSDdtWHcifV19";
const QR_B="AD1.eyJ2IjoxLCJwYWNrIjoiREVNTy1RUi0wMDIiLCJjYXJkcyI6W3siaWQiOjEsImsiOiJfYzNTVzFmS0NjZEluV1ZfVkdUTmNuTDdFTmY1VjVoa0ctc3JwLU1Kd0dJIn0seyJpZCI6MiwiayI6Imx2YWpCVy1makdncDBfMm9sOFlJUVJpQ1phRElUSkhZdEJhVDYzdWFqLUkifSx7ImlkIjo1LCJrIjoiSG5qVDVlOV9Dc0tKLUJMeURFS0ZQU0V4cGxSa1lFT0FER0xfdjVxLU5rdyJ9LHsiaWQiOjksImsiOiIwdFlnVHhaWEx1RWtONXhLeTlDcE02Y2tySTh1UF8tM1ZoTi1EQzlUMWE0In0seyJpZCI6MTMsImsiOiJfRU9ZbjVFNWZ6UUJnUXBfZ1BWQTVhQU03X2sybi04YkRpRGFtNUVENnJFIn1dfQ";
const cards=Array.from({length:20},(_,i)=>({id:i+1,type:TYPE_MAP[i+1]||'',enc:`cards_enc/${String(i+1).padStart(3,'0')}.card`,preview:`previews/${String(i+1).padStart(3,'0')}.webp`}));
const state=loadState();
const decryptedUrls=new Map();
const grid=document.getElementById('albumGrid'),ownedCount=document.getElementById('ownedCount'),gallery=document.getElementById('gallery'),galleryCard=document.getElementById('galleryCard'),galleryMeta=document.getElementById('galleryMeta'),galleryPosition=document.getElementById('galleryPosition'),prevCard=document.getElementById('prevCard'),nextCard=document.getElementById('nextCard'),revealBar=document.getElementById('revealBar'),revealText=document.getElementById('revealText'),toast=document.getElementById('toast'),qrDialog=document.getElementById('qrDialog');
let galleryIndex=0,revealCancelled=false,revealRunning=false;
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const p=JSON.parse(raw);return {keys:p.keys||{},usedQr:new Set(p.usedQr||[])};}}catch(e){}return {keys:{},usedQr:new Set()};}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify({keys:state.keys,usedQr:[...state.usedQr]}));}
function pad(n){return String(n).padStart(3,'0')}
function isUnlocked(id){return typeof state.keys[id]==='string'&&state.keys[id].length>20}
function b64uToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function decodePayload(text){if(typeof text!=='string'||!text.startsWith('AD1.'))throw new Error('QR non riconosciuto');const raw=new TextDecoder().decode(b64uToBytes(text.slice(4)));const p=JSON.parse(raw);if(p.v!==1||typeof p.pack!=='string'||!Array.isArray(p.cards)||p.cards.length<1||p.cards.length>5)throw new Error('Payload QR non valido');for(const item of p.cards){if(!Number.isInteger(item.id)||item.id<1||item.id>20||typeof item.k!=='string')throw new Error('Card QR non valida');}return p;}
async function decryptCard(id,keyText){if(decryptedUrls.has(id))return decryptedUrls.get(id);const c=cards[id-1];const packed=new Uint8Array(await (await fetch(c.enc)).arrayBuffer());if(packed.length<29)throw new Error('File cifrato non valido');const iv=packed.slice(0,12),cipher=packed.slice(12);const key=await crypto.subtle.importKey('raw',b64uToBytes(keyText),{name:'AES-GCM'},false,['decrypt']);const aad=new TextEncoder().encode(`ALBUMDIGITALE:CARD:${pad(id)}`);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv,additionalData:aad},key,cipher);const url=URL.createObjectURL(new Blob([plain],{type:'image/webp'}));decryptedUrls.set(id,url);return url;}
async function imageFor(c){if(!isUnlocked(c.id))return c.preview;try{return await decryptCard(c.id,state.keys[c.id]);}catch(e){return c.preview;}}
async function render(){grid.innerHTML='';for(let i=0;i<cards.length;i++){const c=cards[i],unlocked=isUnlocked(c.id);const slot=document.createElement('article');slot.className='slot'+(unlocked?'':' locked');slot.dataset.id=c.id;const btn=document.createElement('button');btn.type='button';btn.className='card-button';btn.disabled=!unlocked;btn.setAttribute('aria-label',`Card ${pad(c.id)}${c.type?' '+c.type:''}${unlocked?'':' non sbloccata'}`);const src=await imageFor(c);btn.innerHTML=`<div class="card-frame"><img class="card-image" src="${src}" alt="Card ${pad(c.id)}"><div class="shade"></div></div><div class="slot-meta"><span>#${pad(c.id)}</span><span>${c.type}</span></div>`;btn.addEventListener('click',()=>openGallery(i));slot.appendChild(btn);grid.appendChild(slot);}ownedCount.textContent=Object.keys(state.keys).filter(k=>isUnlocked(Number(k))).length;}
async function openGallery(i){galleryIndex=i;await updateGallery();gallery.showModal();}
async function updateGallery(){const c=cards[galleryIndex],locked=!isUnlocked(c.id),src=await imageFor(c);galleryCard.className='gallery-card'+(locked?' locked':'');galleryCard.innerHTML=`<img class="card-image" src="${src}" alt="Card ${pad(c.id)}"><div class="shade"></div>`;galleryPosition.textContent=`${galleryIndex+1} / ${cards.length}`;galleryMeta.textContent=`#${pad(c.id)}${c.type?'  '+c.type:''}${locked?'  ·  NON SBLOCCATA':''}`;prevCard.disabled=galleryIndex===0;nextCard.disabled=galleryIndex===cards.length-1;}
document.getElementById('closeGallery').addEventListener('click',()=>gallery.close());prevCard.addEventListener('click',async()=>{if(galleryIndex>0){galleryIndex--;await updateGallery();}});nextCard.addEventListener('click',async()=>{if(galleryIndex<cards.length-1){galleryIndex++;await updateGallery();}});let x0=null;galleryCard.addEventListener('pointerdown',e=>x0=e.clientX);galleryCard.addEventListener('pointerup',async e=>{if(x0===null)return;const d=e.clientX-x0;x0=null;if(Math.abs(d)<45)return;if(d<0&&galleryIndex<cards.length-1)galleryIndex++;if(d>0&&galleryIndex>0)galleryIndex--;await updateGallery();});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function importQr(text){if(revealRunning)return;let p;try{p=decodePayload(text);}catch(e){toast.textContent=e.message;toast.hidden=false;return;}if(state.usedQr.has(p.pack)){toast.textContent='QR GIÀ USATO SU QUESTO DISPOSITIVO';toast.hidden=false;return;}const targets=[];for(const item of p.cards){if(!isUnlocked(item.id))targets.push(item.id);state.keys[item.id]=item.k;}state.usedQr.add(p.pack);saveState();if(!targets.length){toast.textContent='NESSUNA NUOVA CARD';toast.hidden=false;await render();return;}revealRunning=true;revealCancelled=false;toast.hidden=true;revealBar.hidden=false;qrDialog.close();ownedCount.textContent=Object.keys(state.keys).filter(k=>isUnlocked(Number(k))).length;for(const id of targets){if(revealCancelled)break;await render();const slot=grid.querySelector(`[data-id="${id}"]`);if(!slot)continue;slot.classList.add('locked');const img=slot.querySelector('.card-image');img.src=cards[id-1].preview;slot.scrollIntoView({behavior:'smooth',block:'center'});revealText.textContent=`RIVELAZIONE #${pad(id)}${cards[id-1].type?' '+cards[id-1].type:''}`;await wait(600);if(revealCancelled)break;try{img.src=await decryptCard(id,state.keys[id]);}catch(e){toast.textContent=`ERRORE DECIFRAZIONE #${pad(id)}`;toast.hidden=false;}slot.classList.remove('locked');slot.classList.add('revealing');await wait(800);if(revealCancelled)break;await wait(600);}await render();revealBar.hidden=true;revealRunning=false;toast.textContent=`${targets.length} NUOVE CARD SBLOCCATE`;toast.hidden=false;}
document.getElementById('skipReveal').addEventListener('click',async()=>{revealCancelled=true;revealBar.hidden=true;revealRunning=false;await render();toast.textContent='CARD SBLOCCATE';toast.hidden=false;});
document.getElementById('testQr').addEventListener('click',()=>qrDialog.showModal());document.getElementById('closeQr').addEventListener('click',()=>qrDialog.close());document.getElementById('qrA').addEventListener('click',()=>importQr(QR_A));document.getElementById('qrB').addEventListener('click',()=>importQr(QR_B));document.getElementById('resetDemo').addEventListener('click',async()=>{localStorage.removeItem(STORAGE_KEY);for(const u of decryptedUrls.values())URL.revokeObjectURL(u);decryptedUrls.clear();state.keys={};state.usedQr=new Set();qrDialog.close();toast.textContent='DEMO AZZERATA';toast.hidden=false;await render();});
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
render();
